# Generated by Django 4.2.13 on 2024-10-30 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('gram', models.CharField(max_length=255)),
                ('sort_daytime', models.CharField(blank=True, choices=[('Breakfast', 'breakfast'), ('Lunch', 'lunch'), ('Dinner', 'dinner')], max_length=15, null=True)),
                ('sort', models.CharField(choices=[('Appetizers', 'appetizers'), ('Main Courses', 'main'), ('Side Dishes', 'side'), ('Desserts', 'desserts'), ('Beverages', 'beverages'), ('Soups', 'soups'), ('Salads', 'salads')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('zone', models.CharField(choices=[('Indoors', 'indoors'), ('Outdoors', 'outdoors')], max_length=10)),
                ('sort', models.CharField(choices=[('PIV', 'piv'), ('General', 'general'), ('Appointment', 'appointment')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.table')),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('One', 'one'), ('Two', 'two'), ('Three', 'three'), ('Four', 'four'), ('Five', 'five')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Reserved', 'done'), ('In the basket', 'not_done')], default='not_done', max_length=20)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_dishes', models.ManyToManyField(to='project.dish')),
                ('id_table', models.ManyToManyField(to='project.table')),
            ],
        ),
        migrations.CreateModel(
            name='DishPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.table')),
            ],
        ),
    ]
