# Generated by Django 4.2.13 on 2024-10-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('famely_name', models.CharField(max_length=50)),
                ('bday', models.DateField()),
                ('start_of_work', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('medical_book', models.FileField(upload_to='med_book/')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('gram', models.CharField(max_length=255)),
                ('sort_daytime', models.CharField(blank=True, choices=[('Breakfast', 'breakfast'), ('Lunch', 'lunch'), ('Dinner', 'dinner')], max_length=15, null=True)),
                ('sort', models.CharField(choices=[('Appetizers', 'appetizers'), ('Main Courses', 'main'), ('Side Dishes', 'side'), ('Desserts', 'desserts'), ('Beverages', 'deverages'), ('Soups', 'soups'), ('Salads', 'salads')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('number_of_people', models.FloatField()),
                ('zone', models.CharField(choices=[('Indoors', 'indoors'), ('Outdoors', 'outdoors')], max_length=10)),
                ('sort', models.CharField(choices=[('PIV', 'piv'), ('General', 'general'), ('Appointment', 'appointment')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='table_date_time')),
                ('table', models.ManyToManyField(to='project.table')),
            ],
        ),
        migrations.CreateModel(
            name='DishPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('dish', models.ManyToManyField(to='project.dish')),
            ],
        ),
    ]
