# Generated by Django 4.2.16 on 2024-11-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('Paid', 'paid'), ('In process', 'not paid')], default='not paid', max_length=20),
        ),
    ]
