# Generated by Django 4.2.13 on 2024-12-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartofprivileges',
            name='discount',
            field=models.DecimalField(choices=[(0.9, '10%'), (0.85, '15%'), (0.7, '30%')], decimal_places=2, default='10%', max_digits=3),
        ),
    ]
