# Generated by Django 4.2.16 on 2024-10-31 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_check_id_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='check',
            name='id_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.table'),
        ),
    ]
