# Generated by Django 4.2.16 on 2024-11-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_comment_image_dish_image_stars_id_client_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/dish_img/'),
        ),
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='madia/table_img/'),
        ),
    ]
