# Generated by Django 4.2.13 on 2024-12-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_cartofprivileges_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartofprivileges',
            name='startdate',
            field=models.DateField(auto_now=True),
        ),
    ]
