# Generated by Django 4.2.16 on 2024-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_dish_image_alter_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_img/'),
        ),
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='table_img/'),
        ),
    ]
