# Generated by Django 4.2.13 on 2024-12-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_cartofprivileges_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartofprivileges',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
