# Generated by Django 4.2.16 on 2024-11-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_dish_image_alter_table_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
