# Generated by Django 4.2.13 on 2024-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_cartofprivileges_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartofprivileges',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
