# Generated by Django 4.2.13 on 2024-12-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_cartofprivileges_enddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
