# Generated by Django 4.2.16 on 2024-11-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_dishprice_date_alter_tableprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishprice',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tableprice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
